
@echo off

REM !!! Generated by the fmp-cli 1.65.0.  DO NOT EDIT!

md Retrieval\Assets\3rd\fmp-xtc-retrieval

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-retrieval-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\Retrieval\Assets\3rd\fmp-xtc-retrieval\
